import type { Track } from './types';
import type { Translations } from './i18n/translations';

export const getLocalizedTracks = (t: Translations): Track[] => [
  {
    id: 'mood',
    name: t.tracks.mood,
    color: '#ef4444',
    gradient: 'from-red-500 to-red-300',
    sources: [
      t.sources.mood.joy,
      t.sources.mood.excitement,
      t.sources.mood.anxiety,
      t.sources.mood.sadness,
      t.sources.mood.anger,
      t.sources.mood.calm,
      t.sources.mood.frustration,
      t.sources.mood.gratitude,
    ],
  },
  {
    id: 'sleep',
    name: t.tracks.sleep,
    color: '#f97316',
    gradient: 'from-orange-500 to-orange-300',
    sources: [
      t.sources.sleep.insomnia,
      t.sources.sleep.nightmares,
      t.sources.sleep.restful,
      t.sources.sleep.interrupted,
      t.sources.sleep.deepSleep,
      t.sources.sleep.earlyWake,
      t.sources.sleep.drowsy,
    ],
  },
  {
    id: 'pressure',
    name: t.tracks.pressure,
    color: '#eab308',
    gradient: 'from-yellow-500 to-yellow-300',
    sources: [
      t.sources.pressure.workStress,
      t.sources.pressure.deadlines,
      t.sources.pressure.relationships,
      t.sources.pressure.financial,
      t.sources.pressure.healthConcerns,
      t.sources.pressure.socialObligations,
      t.sources.pressure.selfImposed,
    ],
  },
  {
    id: 'thinking',
    name: t.tracks.thinking,
    color: '#22c55e',
    gradient: 'from-green-500 to-green-300',
    sources: [
      t.sources.thinking.clear,
      t.sources.thinking.foggy,
      t.sources.thinking.racingThoughts,
      t.sources.thinking.creative,
      t.sources.thinking.focused,
      t.sources.thinking.distracted,
      t.sources.thinking.ruminating,
      t.sources.thinking.intrusiveThoughts,
    ],
  },
  {
    id: 'reality',
    name: t.tracks.reality,
    color: '#3b82f6',
    gradient: 'from-blue-500 to-blue-300',
    sources: [
      t.sources.reality.grounded,
      t.sources.reality.detached,
      t.sources.reality.present,
      t.sources.reality.dissociated,
      t.sources.reality.connected,
      t.sources.reality.spacedOut,
      t.sources.reality.aware,
    ],
  },
  {
    id: 'motion',
    name: t.tracks.motion,
    color: '#a855f7',
    gradient: 'from-purple-500 to-purple-300',
    sources: [
      t.sources.motion.active,
      t.sources.motion.restless,
      t.sources.motion.sluggish,
      t.sources.motion.energetic,
      t.sources.motion.tense,
      t.sources.motion.relaxed,
      t.sources.motion.fidgety,
      t.sources.motion.still,
    ],
  },
];
